apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: pg-c
  namespace: default
spec:
  vaultRef:
    name: vault
    namespace: vault
  postgres:
    databaseRef:
      name: pg-c
      namespace: default
    pluginName: "postgresql-database-plugin"
